### ISSUE TITLE
trigger event in a controller

### ISSUE THREAD

**Issue by HermesDev** [kstam/ng-scroll-repeat#3]
Awesome library. It is a great fit for our current project. Way better than ng-infinite scroll. I just love the fact that the display of the elements is only dependent of the html code. Beautiful!

I would like however to trigger an event in my main controller when the bottom of the page is hit.
If there is already a way to do that, could you tell me asap, since I am going to create this feature and do a pull request when it will be done and properly tested.

I planned to extract calculateScrollBottomDiff in another factory under ks.WindowService and tell the ngScrollRepeat directive to use it to still work properly. 

Thanks again for your great lib!

**Comment by HermesDev** [comment]
Looks like it is much simpler than I thought.

**Comment by kstam** [comment]
Thanks for your nice comments and for using the library! 

As you will see your changes have been merged (though I had to make some changes on top of them)

Please also read the comments on the pull request for future reference in case you would like to submit more cool functionality for the lib :)
